### ISSUE TITLE
As a Transmodel API maintainer I want to add official documentation to the Open Data Hub website and other docs

### ISSUE THREAD

**Issue by clezag** [noi-techpark/transmodel-api#4]
Ad an Open Data Hub maintainer, I want to advertise this API to our customers and the public.

Once the API is stable (in use by the NAP), we need to link it on our website and other channels tbd.
Provide customer support with the necessary details so that they can add the documentation.

**Comment by rcavaliere** [comment]
Some additional information on my side:

**End-points to clearly promote**
- End-point for NeTEx data (just parking + sharing data): https://transmodel.api.opendatahub.com/netex
- End-point for SIRI-FM parking data: https://transmodel.api.opendatahub.com/siri-lite/facility-monitoring/parking
- End-point for SIRI-FM sharing data: https://transmodel.api.opendatahub.com/siri-lite/facility-monitoring/sharing

**Reference information**:
NeTEx is the reference EU standard for the exchange of static mobility data. More reference information available here: https://netex-cen.eu/ Italy has defined its own specification, available here: https://github.com/5Tsrl/netex-italian-profile

SIRI is the reference EU standard for the exchange of dynamic mobility data. More reference information available here: https://www.siri-cen.eu/ Italy has defined its own specification, available here: https://github.com/5Tsrl/siri-italian-profile/ In particular, Italy has proposed to use SIRI-FM (Facility Monitoring) for the sharing of parking and sharing mobility data.

**Comment by rcavaliere** [comment]
Waiting that the Customer Care integrates this information in the Open Data Hub web-site
